const data = [
    {
        id: 1,
        country: "Japan",
        viewmap: "https://maps.app.goo.gl/YcXpfeT8V4jf9KDM9",
        place: "Mount Fuji",
        Image: "https://www.planetware.com/wpimages/2022/02/world-top-rated-tourist-attractions-mount-fuji.jpg",
        location: "Fujinomiya",
        description: "Mount Fuji is the most well-known and highest mountain in Japan. Soaring 3,776 meters high, Mount Fuji is one of three Holy Mountains. Hiking to the top of the mountain is a popular thing to do in Japan. Each year, nearly 300,000 people follow one of four routes to the top. One of the most popular things to do is time your hike so that you reach the summit just before sunrise.",
    },
    {
        id: 2,
        country: "Australia",
        viewmap: "https://maps.app.goo.gl/fKbZPgGMyJWrbNhX8",
        place: "Sydney Opera House",
        Image: "https://media.architecturaldigest.com/photos/63d82d299dd44a3242d15ade/16:9/w_2580,c_limit/GettyImages-982774858.jpg",
        location: "Sydney",
        description: "The Sydney Opera House is a multi-venue performing arts center located in Sydney, Australia. It is one of the most famous and distinctive buildings in the world. Designed by Danish architect Jørn Utzon, the Sydney Opera House is a UNESCO World Heritage Site and attracts millions of visitors each year. It is a symbol of Australia's cultural identity and hosts a wide range of performances, including opera, ballet, concerts, and theater.",
    },
    {
        id: 3,
        country: "Norway",
        viewmap: "https://maps.app.goo.gl/LenY3TkKfKGvfMM58",
        place: "Geirangerfjord",
        Image: "https://cdn.pixabay.com/photo/2023/07/05/18/13/mountains-8108961_1280.jpg",
        location: "Geirangerfjord",
        description: "Geirangerfjord is a stunning fjord in Norway that is known for its breathtaking natural beauty. It is one of the most popular tourist destinations in the country and has been designated a UNESCO World Heritage Site. The fjord is surrounded by steep cliffs and lush green mountains, and is home to several picturesque villages. Visitors can take boat tours of the fjord, hike in the surrounding mountains, or simply relax and enjoy the stunning scenery. Geirangerfjord is a must-see destination for anyone visiting Norway.",
    },
    {
        id: 4,
        country: "France",
        viewmap: "https://maps.app.goo.gl/NEn1qxz5aXv6aWQ28",
        place: "Eiffel Tower",
        Image: "https://www.travelandleisure.com/thmb/SPUPzO88ZXq6P4Sm4mC5Xuinoik=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/eiffel-tower-paris-france-EIFFEL0217-6ccc3553e98946f18c893018d5b42bde.jpg",
        location: "Paris",
        description: "The Eiffel Tower is one of the most iconic landmarks in the world and a symbol of Paris. Named after its designer, Gustave Eiffel, the tower was completed in 1889 and has become one of the most visited tourist attractions in the world. The Eiffel Tower is 324 meters tall and offers stunning views of the city from its observation decks. Visitors can also dine in one of the tower's restaurants or enjoy a picnic in the surrounding park. The Eiffel Tower is a must-see destination for anyone visiting Paris.",
    },
    {
        id: 5,
        country: "China",
        viewmap: "https://maps.app.goo.gl/CNF8p4Xrmgdpa36QA",
        place: "Great Wall of China",
        Image: "https://www.travelandleisure.com/thmb/b2-ee45Q1DEjuzOa51XLhJ7Rfmc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/great-wall-china-tourists-GWOC0417-10bddbf0783644c386178f62117b2132.jpg",
        location: "Beijing",
        description: "The Great Wall of China is one of the most famous landmarks in the world and a symbol of China's rich history. The wall was built over several centuries to protect the Chinese empire from invasions by nomadic tribes. Stretching over 13,000 miles, the Great Wall is one",
    },
    {
        id: 6,
        country: "United Kingdom",
        viewmap: "https://maps.app.goo.gl/SKXKHoqA8Je22yDs6",
        place: "Buckingham Palace",
        Image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Buckingham_Palace_UK.jpg/1200px-Buckingham_Palace_UK.jpg",
        location: "London",
        description: "Buckingham Palace is the official residence of the British monarch and one of the most famous landmarks in the United Kingdom. The palace is located in the heart of London and is a popular tourist attraction. Visitors can watch the Changing of the Guard ceremony, tour the State Rooms, and explore the palace's gardens. Buckingham Palace is a must-see destination for anyone visiting London.",
    },
]
export default data;
